import type { Metadata } from 'next'

import { inter } from '@/lib/fonts'
import '@/styles/globals.css'

export const metadata: Metadata = {
  title: 'OBOFUN',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable}`}>{children}</body>
    </html>
  )
}
